### ISSUE TITLE
Respect None build action from Web.config

### ISSUE THREAD

**Issue by coreyasmith** [richardszalay/helix-publishing-pipeline#29]
I've created a root project (`CoreySmith.Project.Website.XConnect`) to deploy xConnect modules to the xConnect web root. At the moment, these projects only contain Model definitions, no code, so I'd rather leave the xConnect `Web.config` out of the solution entirely. If I set the `Build Action` of the `Web.config` in my root project to `None`, I get the following error on build: `No transforms were supplied`. Changing the `Build Action` to `ExcludeFromPackageFiles` by directly modifying the `.csproj` gives the same error.

Adding `<ExcludeFromPackageFiles Include="Web.config" />` to my `PublishSettings.xConnect.targets` file indeed stops the `Web.config` from deploying, but I'd prefer to keep my `PublishSettings.*.targets` files as lean as possible. 

With `<ExcludeFromPackageFiles />`, if you do a one-click publish in Visual Studio, the `Web.config` will still get overwritten; so you actually need to add `<ExcludeFilesFromDeployment>Web.config</ExcludeFilesFromDeployment>` in a `<PropertyGroup />`  in `PublishSettings.*.targets` to make sure that it's not deployed under any circumstance. Supporting the `None` build action would be a lot simpler.

**Comment by richardszalay** [comment]
As per our out-of-band discussion, this is actually a quirk of the standatd WPP / build targets and not a HPP-specific thing. Exclusing the Web.config from publish is the only way of prevent it from being included.
