### ISSUE TITLE
Web.Helix.config transforms also do transforms on /Views/Web.config

### ISSUE THREAD

**Issue by jeneaux** [richardszalay/helix-publishing-pipeline#34]
As discussed on Slack, Helix transforms are being applied to Web.config, and also Views/Web.config, like so:

Foundation/Module/code/Web.Helix.config exists (contains an <appsettings> node)

Project/**MyWebsite**/code/Web.config exists
Project/**MyWebsite**/code/Views/Web.config exists (the Main layout for the site lives here in Views)

HPP (1.4.0) is added to **MyWebsite** project, with default settings. I've configured publish-on-build with a publish profile which copies files locally. After a build, the end result is my <appsettings> nodes being added to both `Web.config` and `Views/Web.config`

I believe the `Views/Web.config` is being included as a candidate for transformation by the CollectWebConfigsToTransform target in Microsoft.Web.Publishing.targets, so not sure if this is an issue with HPP or should be resolved in another way.

I resolved the issue locally by modifying my MyWebsite project to add a target to PreTransformWebConfigDependsOn which explicitly removed `Views/Web.config` from the WebConfigsToTransform identity.

**Comment by richardszalay** [comment]
Resolved and published as 1.4.1
