### ISSUE TITLE
unicorn dll files

### ISSUE THREAD

**Issue by AfshinZavvar** [richardszalay/helix-publishing-pipeline#39]
Richard,
Unicorn is installed on _Foundation.Serialization_. Also one feature has a reference to _Unicorn.Roles_.
I can see that main project has references to all foundations, features and projects and when I build the project, _Foundation.Serialization.dll_ is being deployed but the problem is that Unicorn dlls are not being deployed. Hence, I need to manually copy Unicorn DLLs.
Am I missing any configurations or something has wrongly setup ?

**Comment by AfshinZavvar** [comment]
Thanks Richard 👍 We're using HPP 1.0

As there is a open ticket for config transformations. I need to ask one more thing, 
We've used a mapper for Sitecore view renderings. So there should be a View\web.config with a reference to that mapper assembly. However, It seems HPP intentionally ignores __views/web.config_ .

**Comment by AfshinZavvar** [comment]
Views\web.config is not copied on build

**Comment by richardszalay** [comment]
Can you upgrade to 1.4.2 and see if that resolves the problem?

**Comment by richardszalay** [comment]
Make that 1.4.3, actually.

1.4.2 was published in error.

**Comment by richardszalay** [comment]
I think you'll need to wait for #32 for that
