### ISSUE TITLE
Web.config file in View/{ProjectName}/ is not copied

### ISSUE THREAD

**Issue by luuksommers** [richardszalay/helix-publishing-pipeline#40]
When you put a web.config in Views/{ProjectName}/ it is not copied to the output. In the Sample you can reproduce by adding a web.config file like:

![image](https://user-images.githubusercontent.com/1185823/49612127-fd552000-f9a3-11e8-86f9-7ad6e68b75ba.png) 

in Feature1. With version 1.0.0.0 it is working though, but when you update to the latest, it's broken.

**Comment by richardszalay** [comment]
Thanks for letting me know. Web.config files are ignored to prevent issues with transforms, but it should probably by only ignore files that conflict with transforms.

**Comment by angelakim** [comment]
Using the latest code provided the web.config files are still not being included in the Views folders.
By removing  OR '%(DestinationRelativePath)' == 'Views\$(ProjectConfigFileName)'  from the _HelixModuleWebConfigsToExclude condition in the CollectFilesFromHelixModules target we were able to have web.config files from the Views folder included in the build artifact.
Did I miss a switch that needed be set to prevent the Views web.config files from being excluded?
Thank you for your assistance!
