### ISSUE TITLE
Error when building single-project solutions

### ISSUE THREAD

**Issue by coreyasmith** [richardszalay/helix-publishing-pipeline#46]
In solutions with a single project, Helix Publishing Pipeline fails with the following error:

> The "ResolveModuleContentTargetPath" task was not given a value for the required parameter "Module".	

This error prevents publishes from working both on build and from Visual Studio's one-click publish.

As soon as you add a second project to the solution and reference it from your root project, the error goes away.

**Comment by richardszalay** [comment]
Fixed and released as 1.4.6
