### ISSUE TITLE
AdditionalFilesToRemoveFromTarget feature isn't removing files 

### ISSUE THREAD

**Issue by muso31** [richardszalay/helix-publishing-pipeline#52]
This feature doesnt appear to remove any files from the webroot

Configuration can be found here https://github.com/muso31/Helixbase/blob/master/src/Website/code/Properties/PublishProfiles/Local.pubxml#L21

**Comment by richardszalay** [comment]
Just to clarify before I dive into this, `AdditionalFilesToRemoveFromTarget` only removes files if they aren't going to get published (ie. it's an old, since-renamed, assembly). It also won't work with publishUrl being a URL.

Based on the above, do you think the feature itself is still an issue?

**Comment by muso31** [comment]
Providing AdditionalFilesToRemoveFromTarget is a webroot clean... I've got the publishUrl set to a path. If I rename a binary in the webroot and then publish with hpp the assembly still exists in the webroot even though it should be caught in the wildcard in Directory.build.props

**Comment by muso31** [comment]
Example is... 

Path config: https://github.com/muso31/Helixbase/blob/master/src/Website/code/Properties/PublishProfiles/Local.pubxml#L12

Wildcard: https://github.com/muso31/Helixbase/blob/master/src/Website/code/Properties/PublishProfiles/Local.pubxml#L22

Unless it should be **Website\bin\Helixbase.*.dll** I believe it could be a defect

**Comment by richardszalay** [comment]
No, `bin\Helixbase.*.dll` is correct. Sounds like a bug.

(I'm assuming you haven't run your rename script, right? That wouldn't catch the old file name)

**Comment by muso31** [comment]
Yep all vanilla, no rename!

**Comment by richardszalay** [comment]
I'll take a look. Btw, if you set define a  `EnablePackageProcessLoggingAndAssert` property as `true`, the files to be removed will be emitted to `AdditionalFilesToRemoveFromPublish.txt` in the `obj\Release\Package\Logs` (from memory) directory

**Comment by rkeitel** [comment]
It doesn't work. I also tried to set `EnablePackageProcessLoggingAndAssert` to `true`, but the file `AdditionalFilesToRemoveFromPublish.txt` is missing after publishing.

**Comment by richardszalay** [comment]
@rkeitel What version of HPP are you using, and what is your publishing target (package, filesystem, etc)?

**Comment by richardszalay** [comment]
@rkeitel Also, is `DeleteExistingFiles` set to `true` in your publish profile? HPP's remove additional files functionality only runs if WPP isn't going to just nuke everything (as there's be no point).
