### ISSUE TITLE
Sitecore 9.2 assembly version list don't work with excludes : an extra header was introduced

### ISSUE THREAD

**Issue by BasLijten** [richardszalay/helix-publishing-pipeline#69]
with Sitecore 9.2 (and maybe 9.1, didn't check), the lists couldn't be used anymore. With 4 fields of information (Filename,Version,FileVersion,InfoVersion) instead of 3 (Filename,Version,FileVersion,InfoVersion) the list couldn't be parsed anymore. This happened due to an explicit check on the amount of fields.

**Comment by richardszalay** [comment]
Thanks for the heads up. I'll try to fix it in the next few days but feel free to PR if you need it in a hurry - just add a specific unit test for it in the tasks project.

**Comment by BasLijten** [comment]
Ah PR is being prepared. My previous one contained 100+ Commits for some reason

**Comment by BasLijten** [comment]
PR #71 solves this issue. Succesfully tested

**Comment by richardszalay** [comment]
Released as 1.5.6

**Comment by markgibbons25** [comment]
Looks to be an issue in 10.1 - manually changing the header (first line) in the `Sitecore.Platform.Assemblies 10.1.x rev. xxx.csv` file to this fixes it:
`Filename,FileVersion,Version,InfoVersion`
